name: create model release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install onnx
        run: |
          pip install onnx
      - name: check files exist
        run: |
          from pathlib import Path
          import os
          import onnx
          model_dir = Path('model')
          assert model_dir.exists() and model_dir.is_dir() ,  'Did not find model directory!'
          files = os.listdir(model_dir)
          assert 'vocab.txt' in files, 'Did not find a vocab.txt file'
          assert 'modelcard.md' in files,  'Did not find a model card in the model directory'
          suffixes = [Path(file).suffix for file in files]
          assert '.onnx' in suffixes, 'Did not find onnx model in the model directory!'
        

          print('checking model onnx model...')
          f = list(model_dir.rglob("*.onnx"))[0]
          model = onnx.load(f)
          onnx.checker.check_model(model, full_check=True)
        shell: python

      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYYMMDD
      - name: Use current time
        env:
          TIME: "${{ steps.current-time.outputs.formattedTime }}"
        run: echo $TIME 
      - uses: papeloto/action-zip@v1
        with:
          files: model/
          recursive: false
          dest: ${{ steps.current-time.outputs.formattedTime }}.zip
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.current-time.outputs.formattedTime }}.zip
          name:  ${{ steps.current-time.outputs.formattedTime }}
          tag_name:  ${{ steps.current-time.outputs.formattedTime }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
